In [6]:
import numpy as np

In [7]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [8]:
print(arr.dtype)

int64


In [9]:
arr2 = np.array([1,2,3,4,5],dtype=np.int16)
arr2

array([1, 2, 3, 4, 5], dtype=int16)

In [10]:
Z=np.zeros(5)
Z

array([0., 0., 0., 0., 0.])

In [11]:
ar=np.arange(0,10,1)
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
ran=np.random.rand(4)
ran

array([0.97052118, 0.09486066, 0.31674302, 0.98920383])

In [13]:
ln=np.linspace(0,100,10)
ln

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

**2D ARRAYS**

In [14]:
ar2=np.array([[1,2,3],[4,5,6],[7,8,9]])
ar2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
z1=np.zeros([5,5])
z1

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
o1=np.ones([5,5])
o1

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [17]:
I=np.eye(5)
I

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [18]:
r1=np.random.rand(4,5)
r1

array([[0.4357444 , 0.00788536, 0.84481513, 0.0101962 , 0.27698872],
       [0.03258219, 0.72446789, 0.30842598, 0.74799036, 0.96630582],
       [0.16705234, 0.88528916, 0.04574329, 0.23587352, 0.09335102],
       [0.10508753, 0.61584672, 0.99836882, 0.98598015, 0.74396058]])

In [19]:
ar
ar2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
ar2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
print(ar.size)

10


In [23]:
print(ar2.size)

9


In [24]:
print(ar.shape)

(10,)


In [25]:
print(ar2.shape)

(3, 3)


**OPERATIONS IN ARRAY**COPY RESHAPE SORT

In [26]:
ar3=np.copy(ar2)
ar3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
ar3[2,2]=10

In [28]:
ar3

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8, 10]])

In [29]:
ar3[1,2]=12
ar3[0,1]=15
ar3

array([[ 1, 15,  3],
       [ 4,  5, 12],
       [ 7,  8, 10]])

In [30]:
ar3=np.sort(ar3)
ar3


array([[ 1,  3, 15],
       [ 4,  5, 12],
       [ 7,  8, 10]])

In [31]:
ar3=np.sort(ar3,axis=0)
ar3

array([[ 1,  3, 10],
       [ 4,  5, 12],
       [ 7,  8, 15]])

In [32]:
ar3.sum()

np.int64(65)

In [33]:
ar3.sum(axis=0)

array([12, 16, 37])

In [34]:
ar3.sum(axis=1)

array([14, 21, 30])

In [35]:
ar4=np.random.rand(99)
ar4

array([0.70992085, 0.82072995, 0.46848903, 0.73345591, 0.84379859,
       0.72424687, 0.10033381, 0.87134199, 0.70858813, 0.45827687,
       0.86944245, 0.54444532, 0.5538288 , 0.29789516, 0.52789647,
       0.86528144, 0.53121972, 0.23346524, 0.28499613, 0.80432004,
       0.67166896, 0.83221991, 0.15638103, 0.58722994, 0.27536536,
       0.12773165, 0.47183208, 0.89102586, 0.5382469 , 0.31772499,
       0.17655734, 0.01000097, 0.36738066, 0.90935183, 0.05692884,
       0.78241803, 0.24174003, 0.53805178, 0.77953945, 0.85479385,
       0.81218113, 0.06361923, 0.55328425, 0.44917649, 0.91328352,
       0.41836822, 0.80638538, 0.59544595, 0.78895844, 0.03341558,
       0.34384859, 0.55777259, 0.32153408, 0.15629452, 0.67531255,
       0.73738117, 0.60493845, 0.38426234, 0.14664674, 0.62084058,
       0.72473312, 0.24598193, 0.60056771, 0.94212343, 0.54217415,
       0.22373431, 0.57969193, 0.99047521, 0.73574804, 0.38178275,
       0.85144591, 0.25838733, 0.21406254, 0.68264976, 0.71585

In [36]:
ar4.size

99

In [37]:
ar4=ar4.reshape(11,9)

In [38]:
ar4.size

99

In [39]:
ar4.shape

(11, 9)

In [40]:
ar4

array([[0.70992085, 0.82072995, 0.46848903, 0.73345591, 0.84379859,
        0.72424687, 0.10033381, 0.87134199, 0.70858813],
       [0.45827687, 0.86944245, 0.54444532, 0.5538288 , 0.29789516,
        0.52789647, 0.86528144, 0.53121972, 0.23346524],
       [0.28499613, 0.80432004, 0.67166896, 0.83221991, 0.15638103,
        0.58722994, 0.27536536, 0.12773165, 0.47183208],
       [0.89102586, 0.5382469 , 0.31772499, 0.17655734, 0.01000097,
        0.36738066, 0.90935183, 0.05692884, 0.78241803],
       [0.24174003, 0.53805178, 0.77953945, 0.85479385, 0.81218113,
        0.06361923, 0.55328425, 0.44917649, 0.91328352],
       [0.41836822, 0.80638538, 0.59544595, 0.78895844, 0.03341558,
        0.34384859, 0.55777259, 0.32153408, 0.15629452],
       [0.67531255, 0.73738117, 0.60493845, 0.38426234, 0.14664674,
        0.62084058, 0.72473312, 0.24598193, 0.60056771],
       [0.94212343, 0.54217415, 0.22373431, 0.57969193, 0.99047521,
        0.73574804, 0.38178275, 0.85144591, 0.25838733],


In [41]:
ar3

array([[ 1,  3, 10],
       [ 4,  5, 12],
       [ 7,  8, 15]])

In [42]:
ar3=ar3.T
ar3

array([[ 1,  4,  7],
       [ 3,  5,  8],
       [10, 12, 15]])

In [43]:
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
np.append(ar,10)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [45]:
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
ar=np.delete(ar,6,axis=0)

In [47]:
ar

array([0, 1, 2, 3, 4, 5, 7, 8, 9])

In [48]:
ar=np.insert(ar,6,6)
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
ar2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [50]:
ar3

array([[ 1,  4,  7],
       [ 3,  5,  8],
       [10, 12, 15]])

In [51]:
ar4=np.concatenate((ar2,ar3),axis=0)
ar4

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [ 1,  4,  7],
       [ 3,  5,  8],
       [10, 12, 15]])

In [52]:
ar5=np.concatenate((ar2,ar3),axis=1)
ar5

array([[ 1,  2,  3,  1,  4,  7],
       [ 4,  5,  6,  3,  5,  8],
       [ 7,  8,  9, 10, 12, 15]])

In [53]:
np.split(ar4,3)

[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[7, 8, 9],
        [1, 4, 7]]),
 array([[ 3,  5,  8],
        [10, 12, 15]])]

In [54]:
ar6=np.split(ar4,3)
ar6

[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[7, 8, 9],
        [1, 4, 7]]),
 array([[ 3,  5,  8],
        [10, 12, 15]])]

In [55]:
ar6[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [56]:
ar6[2]

array([[ 3,  5,  8],
       [10, 12, 15]])

In [57]:
ar6[0][0][0]

np.int64(1)

**SCALAR EXPRESSIONS**
Multiply,divide,power,add,substract

In [58]:
ar5

array([[ 1,  2,  3,  1,  4,  7],
       [ 4,  5,  6,  3,  5,  8],
       [ 7,  8,  9, 10, 12, 15]])

In [59]:
np.add(ar5,1)

array([[ 2,  3,  4,  2,  5,  8],
       [ 5,  6,  7,  4,  6,  9],
       [ 8,  9, 10, 11, 13, 16]])

**VECTOR OPERATIONS**

In [63]:
ar6

[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[7, 8, 9],
        [1, 4, 7]]),
 array([[ 3,  5,  8],
        [10, 12, 15]])]

In [66]:
ar7 = np.add(ar6[0],ar6[1])
ar8 = np.multiply(ar6[0],ar6[1])
ar8

array([[ 7, 16, 27],
       [ 4, 20, 42]])

In [67]:
ar9 = np.divide(ar6[0],ar6[1])
ar9

array([[0.14285714, 0.25      , 0.33333333],
       [4.        , 1.25      , 0.85714286]])

In [68]:
np.ceil(ar9)

array([[1., 1., 1.],
       [4., 2., 1.]])

In [69]:
np.floor(ar9)

array([[0., 0., 0.],
       [4., 1., 0.]])

In [70]:
np.round(ar9)

array([[0., 0., 0.],
       [4., 1., 1.]])

**Statistics**

In [71]:
np.mean(ar5)

np.float64(6.111111111111111)

In [72]:
np.mean(ar5,axis=0)

array([ 4.        ,  5.        ,  6.        ,  4.66666667,  7.        ,
       10.        ])

In [73]:
np.mean(ar5,axis=1)

array([ 3.        ,  5.16666667, 10.16666667])

In [74]:
np.median(ar5)

np.float64(5.5)

In [75]:
np.median(ar5,axis=1)

array([2.5, 5. , 9.5])

In [76]:
np.min(ar5)

np.int64(1)

In [77]:
np.min(ar5,axis=0)

array([1, 2, 3, 1, 4, 7])

In [78]:
np.max(ar5,axis=0)

array([ 7,  8,  9, 10, 12, 15])

In [79]:
ar10=np.array([2,5,3,8,0,4,1,6,9])

In [80]:
ar5

array([[ 1,  2,  3,  1,  4,  7],
       [ 4,  5,  6,  3,  5,  8],
       [ 7,  8,  9, 10, 12, 15]])